/** Public support / contact (site + legal). */
export const CONTACT_EMAIL = "pathly.ai.cs@gmail.com";
export const CONTACT_MAILTO = `mailto:${CONTACT_EMAIL}`;

export const APP_STORE_URL =
  "https://apps.apple.com/app/pathbuild/id6743108030";

export const APP_NAME = "PathBuild";

export const APP_TAGLINE =
  "AI career discovery for iOS. Find your fit. Discover who's hiring.";

export const APP_HERO_TITLE =
  "Discover the career that actually fits you.";

export const APP_HERO_SUB =
  "Answer a few smart questions. AI surfaces the careers that match your interests, strengths, and values — then shows you the companies hiring for them.";

// ─── Pricing ──────────────────────────────────────────────────────────────────

export const MONTHLY_PRICE = "$14.99";
export const ANNUAL_PRICE = "$24.99";
// Both plans now include the same free trial length.
export const TRIAL_DAYS = 3;
export const MONTHLY_TRIAL_DAYS = TRIAL_DAYS;
export const ANNUAL_TRIAL_DAYS = TRIAL_DAYS;

export const PRICING_HEADLINE = "Start free. Go Pro when you're ready.";
export const PRICING_SUB =
  "Browse, save companies, and run the career quiz for free. Upgrade to PathBuild Pro for salary intel, AI tailoring, interview prep, and side-by-side comparisons.";
export const PRICING_FOOTNOTE =
  "Both plans include a 3-day free trial. Payment charged to Apple ID. Cancel anytime in Settings.";

// ─── Free vs Pro ─────────────────────────────────────────────────────────────

export const FREE_FEATURES = [
  "AI career quiz — built around how you actually think",
  "Personalized career matches with fit scores",
  "Discover companies hiring for your matched careers",
  "Unlimited company saves",
  "Full job search & posting details",
  "Custom application stages & reminders",
  "Private by design — your data stays yours",
];

export const PRO_FEATURES = [
  "Everything in Free",
  "Salary intel — real comp benchmarks for your target roles",
  "AI tailoring — one-paragraph resume note generated per company",
  "Interview prep — practice questions tuned to your target role",
  "Job-fit analysis — AI reads the posting, tells you exactly where you fit",
  "Side-by-side company comparisons — pay, culture, growth",
  "Every future update, included",
];

// ─── Feature cards ───────────────────────────────────────────────────────────

export const FEATURE_CARDS = [
  {
    title: "Smart Career Quiz",
    body: "Five minutes of thoughtful questions about your interests, values, working style, and strengths. Every answer trains your personal fit profile.",
  },
  {
    title: "AI Career Match",
    body: "PathBuild's AI matches your profile to hundreds of real career paths and ranks them by fit. See why each one suits you, what skills you'd build, and where it leads.",
  },
  {
    title: "Company Discovery",
    body: "For every matched career, discover companies actively hiring — sorted by culture fit, comp band, location, and stage. No more generic job board grind.",
  },
  {
    title: "Salary Intel",
    body: "Real compensation benchmarks for every company and role in your list. Know what the market pays before you ever walk into a conversation. Pro.",
  },
  {
    title: "AI Resume Tailoring",
    body: "One focused paragraph — generated by AI for each company you're eyeing — highlighting exactly why you're a fit. Easy to drop into any application. Pro.",
  },
  {
    title: "Side-by-Side Compare",
    body: "Stack any two companies on pay, culture, growth trajectory, and requirements. Make the decision with real data, not gut feel. Pro.",
  },
];

// ─── How It Works ────────────────────────────────────────────────────────────

export const HOW_IT_WORKS_STEPS = [
  {
    title: "Answer a few questions",
    body: "A five-minute smart quiz about how you think, what you value, and what you're naturally good at. No résumé required.",
  },
  {
    title: "Get matched to careers",
    body: "AI surfaces the career paths that actually fit you — each with a fit score, what you'd do day-to-day, and the path to get there.",
  },
  {
    title: "Discover who's hiring",
    body: "For every match, see real companies hiring for that role. Sorted by fit, ready for you to explore and save.",
  },
  {
    title: "Track your applications",
    body: "Save companies, set custom stages, and get reminders so nothing falls through the cracks.",
  },
  {
    title: "Nail the application with Pro",
    body: "Salary intel, AI-tailored resume notes, interview prep questions, and job-fit analysis — every tool you need to land the role.",
  },
];

// ─── FAQ ─────────────────────────────────────────────────────────────────────

export const FAQ_ITEMS = [
  {
    q: "What is PathBuild?",
    a: "PathBuild is an AI career discovery app for iOS. It asks you a few smart questions, matches you to careers that genuinely fit your interests and strengths, then surfaces companies actively hiring for those roles.",
  },
  {
    q: "How is it different from a career quiz I'd find online?",
    a: "Most quizzes spit out a vague archetype. PathBuild uses AI to give you specific, ranked career matches with fit scores — then closes the loop by showing real companies hiring for each one. Discovery → action, in one app.",
  },
  {
    q: "What's free?",
    a: "The core career discovery experience is completely free: the quiz, AI career matching, company discovery, unlimited saves, job search, and custom application stages. Free forever.",
  },
  {
    q: "What does PathBuild Pro include?",
    a: "Pro unlocks salary intel, AI-tailored resume notes, interview prep questions, job-fit analysis, and side-by-side company comparisons — everything you need to go from discovery to offer.",
  },
  {
    q: "How much does PathBuild Pro cost?",
    a: `PathBuild Pro is $${MONTHLY_PRICE.replace("$","")}/month or $${ANNUAL_PRICE.replace("$","")}/year. Both plans include a ${TRIAL_DAYS}-day free trial — no charge until the trial ends.`,
  },
  {
    q: "How do I cancel?",
    a: "You can cancel anytime in Settings → Apple ID → Subscriptions → PathBuild. Cancellation takes effect at the end of the current billing period. You keep Pro access until it expires.",
  },
  {
    q: "Is my data private?",
    a: "Yes. Your quiz answers and career profile are private and encrypted. We never sell your data, never share it with recruiters, and you can delete everything from inside the app at any time.",
  },
  {
    q: "What platforms is PathBuild available on?",
    a: "PathBuild is currently available on iOS (iPhone and iPad). More platforms are on the roadmap.",
  },
];
